name: Ubuntu CI

on:
  push:
    branches: [ "vulkan" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install deps
      run: |
        sudo add-apt-repository universe
        sudo apt-get install build-essential git make \
        pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
        libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
        libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
        libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
        libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libfuse2t64
    - name: Build and pack Iris
      run: |
        git fetch --all --tags
        cmake -S . -B build
        cmake --build build -j8
        sudo cmake --install build
        mkdir dist
        mv ./build/iris ./dist
        mkdir appimage
        mv ./build/*.AppImage ./appimage
    - uses: actions/upload-artifact@v4
      with:
        name: iris-latest-linux
        path: ./dist
    - uses: actions/upload-artifact@v4
      with:
        name: iris-latest-linux-appimage
        path: ./appimage


